#!/bin/bash
## Hostname, IP or FQDN.
HOST_NAME=127.0.0.1

## LDAP server configuration
## Comment these variables out if you have a running ldap server.
## If SLAPD_DOMAIN and SLAPD_PASSWORD is set,
## LDAP_SERVER and LDAP_ACCOUNTBASE will be overwritten automatically.
SLAPD_DOMAIN=demo.com
SLAPD_PASSWORD=secret

## LDAP_SERVER and LDAP_ACCOUNTBASE become unnecessary
## if SLAPD_DOMAIN and SLAPD_PASSWORD have values.
## LDAP Server IP or FQDN.
LDAP_SERVER=127.0.0.1
## LDAP account baseDN
LDAP_ACCOUNTBASE=ou=accounts,dc=demo,dc=com

## Gerrit administrator's uid in LDAP
GERRIT_ADMIN_UID=admin
GERRIT_ADMIN_PWD=passwd
GERRIT_ADMIN_EMAIL=admin@demo.com

## Sonatype Nexus repository URL
## Jenkins use this URL as maven mirror.
## Uncomment this variable if there's a nexus server.
#NEXUS_WEBURL=http://127.0.0.1:8080/content/groups/public
